# Generated by Django 4.2.7 on 2026-01-04 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_fix_country_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
    ]
