# Generated by Django 4.2.7 on 2026-01-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_userprofile_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyresponse',
            options={'ordering': ['-started_at'], 'verbose_name': 'Survey Response', 'verbose_name_plural': 'Survey Responses'},
        ),
    ]
