# Generated by Django 4.2.7 on 2026-01-18 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_alter_surveyresponse_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, help_text='Difficulty level of the survey (1-10)', validators=[django.core.validators.MinValueValidator(1, message='Level must be at least 1'), django.core.validators.MaxValueValidator(10, message='Level cannot be greater than 10')]),
        ),
    ]
