# Generated by Django 4.2.7 on 2026-01-18 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0006_survey_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='luckydrawentry',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='luckydrawentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='luckydrawentry',
            name='guessed_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='luckydrawentry',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='luckydrawentry',
            name='prize',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='luckydrawentry',
            name='winning_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='luckydrawentry',
            name='month',
        ),
        migrations.RemoveField(
            model_name='luckydrawentry',
            name='selected_number',
        ),
        migrations.RemoveField(
            model_name='luckydrawentry',
            name='year',
        ),
        migrations.CreateModel(
            name='UserSurveyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('last_completed', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveycategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Survey Progress',
                'unique_together': {('user', 'category', 'level')},
            },
        ),
    ]
