# Generated by Django 4.2.7 on 2026-01-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_alter_luckydrawentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='luckydrawentry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Lucky Draw Entries'},
        ),
        migrations.AddField(
            model_name='luckydrawentry',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
