# Generated by Django 4.2.7 on 2026-01-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_alter_luckydrawentry_options_luckydrawentry_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luckydrawentry',
            name='level',
        ),
        migrations.AddField(
            model_name='luckydrawentry',
            name='surveys_at_play',
            field=models.PositiveIntegerField(default=0, help_text='Total surveys completed when this entry was created'),
            preserve_default=False,
        ),
    ]
