# Generated by Django 4.2.7 on 2026-03-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_emailverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveycategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
