# Generated by Django 4.2.7 on 2026-03-28 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_alter_surveycategory_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('surveys_completed', 'Surveys Completed'), ('points_earned', 'Points Earned')], max_length=32)),
                ('threshold', models.PositiveIntegerField()),
                ('achieved_value', models.PositiveIntegerField()),
                ('prize_name', models.CharField(max_length=255)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Milestone Achievement',
                'verbose_name_plural': 'Milestone Achievements',
                'ordering': ['-achieved_at'],
                'unique_together': {('user', 'milestone_type', 'threshold')},
            },
        ),
    ]
