# Generated by Django 4.2.7 on 2026-07-02 05:42

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import surveys.models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0023_walletwithdrawalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='A URL-friendly version of the title. Will be automatically generated from the title.', max_length=220, unique=True)),
                ('author', models.CharField(blank=True, default='Sudraw Team', max_length=100)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown on the Journal listing page.')),
                ('content', ckeditor.fields.RichTextField(help_text='Full article content (supports rich text)')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to=surveys.models.journal_image_upload_path)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal Post',
                'verbose_name_plural': 'Journal Posts',
                'ordering': ['-published_at'],
            },
        ),
    ]
