# Generated by Django 4.2.7 on 2026-07-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0025_privacypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalpost',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Survey category this post relates to. Auto-detected from the title if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_posts', to='surveys.surveycategory'),
        ),
    ]
