# Generated by Django 4.2.7 on 2026-07-14 17:17

from django.db import migrations, models
from django.utils.text import slugify
import django.db.models.deletion
import surveys.models


COUNTRY_PREFIX_ALIASES = {
    'United Kingdom': ['U.K.', 'UK'],
    'United States of America': ['U.S.A.', 'USA', 'US'],
}

# Shared between the "clear" and "assign" data steps below, which run as
# separate RunPython operations but in the same process during `migrate`.
_post_category_names = {}


def _strip_country_prefix(name, country_name):
    stripped = (name or '').strip()
    candidates = [country_name] + COUNTRY_PREFIX_ALIASES.get(country_name, [])
    for prefix in candidates:
        if prefix and stripped.lower().startswith(prefix.lower() + ' '):
            return stripped[len(prefix):].strip()
    return stripped


def _normalize(name):
    return ' '.join(name.split())


def _unique_slug(name, used_slugs):
    slug = slugify(name)
    original = slug
    counter = 1
    while slug in used_slugs:
        slug = f'{original}-{counter}'
        counter += 1
    used_slugs.add(slug)
    return slug


def populate_journal_categories(apps, schema_editor):
    """Build a country-agnostic JournalCategory list from the unique (deduped) SurveyCategory names."""
    SurveyCategory = apps.get_model('surveys', 'SurveyCategory')
    JournalCategory = apps.get_model('surveys', 'JournalCategory')

    used_slugs = set(JournalCategory.objects.values_list('slug', flat=True))
    seen_names = set()
    for survey_category in SurveyCategory.objects.select_related('country').order_by('country__name', 'name'):
        country_name = survey_category.country.name if survey_category.country_id else ''
        base_name = _normalize(_strip_country_prefix(survey_category.name, country_name))
        if not base_name:
            continue
        key = base_name.lower()
        if key in seen_names:
            continue
        seen_names.add(key)
        JournalCategory.objects.create(
            name=base_name,
            slug=_unique_slug(base_name, used_slugs),
            image=survey_category.image,
        )


def clear_journalpost_category(apps, schema_editor):
    """Snapshot each post's intended (country-agnostic) category name, then null the old FK
    before its target table is switched from SurveyCategory to JournalCategory."""
    JournalPost = apps.get_model('surveys', 'JournalPost')
    posts = JournalPost.objects.select_related('category', 'category__country').exclude(category__isnull=True)
    for post in posts:
        country_name = post.category.country.name if post.category.country_id else ''
        _post_category_names[post.pk] = _normalize(_strip_country_prefix(post.category.name, country_name))
    JournalPost.objects.exclude(category__isnull=True).update(category=None)


def assign_journalpost_categories(apps, schema_editor):
    """Re-point each post at the matching JournalCategory using the names snapshotted above."""
    JournalPost = apps.get_model('surveys', 'JournalPost')
    JournalCategory = apps.get_model('surveys', 'JournalCategory')
    lookup = {jc.name.lower(): jc.pk for jc in JournalCategory.objects.all()}
    for post_pk, base_name in _post_category_names.items():
        jc_pk = lookup.get(base_name.lower())
        if jc_pk:
            JournalPost.objects.filter(pk=post_pk).update(category_id=jc_pk)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0027_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='A URL-friendly version of the name. Will be automatically generated from the name.', max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=surveys.models.journal_category_image_upload_path)),
                ('order', models.PositiveIntegerField(default=0, help_text='Categories will be ordered by this value in ascending order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Journal Category',
                'verbose_name_plural': 'Journal Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RunPython(populate_journal_categories, noop),
        migrations.RunPython(clear_journalpost_category, noop),
        migrations.AlterField(
            model_name='journalpost',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Journal category this post relates to. Auto-detected from the title if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_posts', to='surveys.journalcategory'),
        ),
        migrations.RunPython(assign_journalpost_categories, noop),
    ]
