# Generated by Django 4.2.7 on 2026-08-09 13:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0028_journalcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Full article content (supports rich text and inline images)'),
        ),
    ]
