# Generated by Django 4.2.7 on 2026-09-07 04:28

from django.db import migrations, models
import django.db.models.deletion
import surveys.models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0029_alter_journalpost_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='Where the advert links to when clicked.')),
                ('image', models.ImageField(blank=True, null=True, upload_to=surveys.models.advertiser_image_upload_path)),
                ('description', models.TextField(blank=True, help_text='Short line shown under the advert image.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to stop showing this advert.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Show only on surveys in this category. Leave blank to show in every category.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisers', to='surveys.surveycategory')),
                ('country', models.ForeignKey(blank=True, help_text='Show only to users in this country. Leave blank to show in every country.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisers', to='surveys.country')),
            ],
            options={
                'verbose_name': 'Advertiser',
                'verbose_name_plural': 'Advertisers',
                'ordering': ['name'],
            },
        ),
    ]
