# Generated by Django 4.2.7 on 2026-09-07 14:24

from django.db import migrations, models
import django.db.models.deletion
import surveys.models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0030_advertiser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='Where the advert links to when clicked.')),
                ('image', models.ImageField(blank=True, null=True, upload_to=surveys.models.direct_marketing_image_upload_path)),
                ('description', models.TextField(blank=True, help_text='Short line shown under the advert name.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to stop showing this advert.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional. Recorded for your own reporting - the home page has no category, so this does not affect where the advert shows.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_marketing_ads', to='surveys.surveycategory')),
                ('country', models.ForeignKey(blank=True, help_text='Show only to signed-in users in this country. Leave blank to show to everyone, including signed-out visitors.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_marketing_ads', to='surveys.country')),
            ],
            options={
                'verbose_name': 'Direct Marketing Advert',
                'verbose_name_plural': 'Direct Marketing Adverts',
                'ordering': ['name'],
            },
        ),
    ]
