# Generated by Django 4.2.7 on 2026-09-07 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0031_directmarketing'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Show only on surveys in these categories. Leave empty to show in every category.', related_name='advertiser_targets', to='surveys.surveycategory'),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='Show only to users in these countries. Leave empty to show in every country.', related_name='advertiser_targets', to='surveys.country'),
        ),
        migrations.AddField(
            model_name='directmarketing',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Optional. Recorded for your own reporting - the home page has no category, so this does not affect where the advert shows.', related_name='direct_marketing_targets', to='surveys.surveycategory'),
        ),
        migrations.AddField(
            model_name='directmarketing',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='Show only to signed-in users in these countries. Leave empty to show to everyone, including signed-out visitors.', related_name='direct_marketing_targets', to='surveys.country'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Deprecated - replaced by categories.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisers', to='surveys.surveycategory'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Deprecated - replaced by countries.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisers', to='surveys.country'),
        ),
        migrations.AlterField(
            model_name='directmarketing',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Deprecated - replaced by categories.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_marketing_ads', to='surveys.surveycategory'),
        ),
        migrations.AlterField(
            model_name='directmarketing',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Deprecated - replaced by countries.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_marketing_ads', to='surveys.country'),
        ),
    ]
