# Generated by Django 4.2.7 on 2026-09-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0033_copy_advert_targets_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='category',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='directmarketing',
            name='category',
        ),
        migrations.RemoveField(
            model_name='directmarketing',
            name='country',
        ),
    ]
