# Generated by Django 4.2.7 on 2026-09-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0034_remove_advert_single_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryluckydrawconfig',
            name='monthly_winner_cap',
            field=models.PositiveIntegerField(blank=True, help_text='Max lucky draw winners per calendar month for this country. Leave blank for no cap.', null=True),
        ),
    ]
