# Generated by Django 4.2.7 on 2026-09-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0036_seed_monthly_draw_prizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryluckydrawconfig',
            name='monthly_prize_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly draw prize for this country, in the currency above. Leave blank if this country does not take part in the Monthly draw.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='countryluckydrawconfig',
            name='monthly_winner_cap',
            field=models.PositiveIntegerField(blank=True, help_text='Max Monthly draw winners per calendar month for this country. Leave blank for no cap.', null=True),
        ),
        migrations.AlterField(
            model_name='luckydrawentry',
            name='draw_type',
            field=models.CharField(choices=[('survey', 'Survey'), ('poll', 'Poll'), ('monthly', 'Monthly')], db_index=True, default='survey', help_text='Whether this lucky draw play was earned from surveys or polls.', max_length=10),
        ),
    ]
